/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hir;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ugent
 */
public class EXAMENGUIWIJZEGEN extends javax.swing.JFrame {
    private ExamenGUI2 kop;

    /**
     * Creates new form EXAMENGUIWIJZEGEN
     */
    public EXAMENGUIWIJZEGEN() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        beschikbareAssistenten = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Beschikbare assistenten:");

        jScrollPane1.setViewportView(beschikbareAssistenten);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MET WELKE ASSISTENT WILT U WISSELEN?");

        jButton1.setText("Wisselen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      EXAMENGUIGOEDKEURING a = new EXAMENGUIGOEDKEURING();
      a.show();
    }//GEN-LAST:event_jButton1ActionPerformed

   
    
    //nadat assistent examensessie heeft ingegeven om te wisselen , wordt die in de lijst ingestoken .
    public void setAssisten() throws DBException{
        DefaultListModel dlm = new DefaultListModel();
        for(Assistent a : DBAssistent.getAssistenten()){
            if(a.isStatusVrij() && a.isSlotnrVrij(kop.getTeWisselenExamenSessie().getSlot().getSlotNr(), a))
                dlm.addElement(a.toString());
        }
       beschikbareAssistenten.setModel(dlm);
        
    }
   
    
    
    
   
    public void setExamenSessiesBeschikbaar(ArrayList<String> a){
        DefaultListModel b = new DefaultListModel();
        for(String c : a){
            b.addElement(c);
        }
        beschikbareAssistenten.setModel(b);
    }
    
    
    public void surveillantiesUitwisselen() throws DBException{
       Assistent a = DBAssistent.getAssistent(kop.getAssistentNummer());
       Assistent b = DBAssistent.getAssistent(AssistenNummerNemen(getWisselAssistent()));
        for(ExamenSessie d : a.getToegewezenSessies()){
            if(kop.getTeWisselenExamenSessie().equals(d.toString())){
                a.getToegewezenSessies().remove(d);
                
            }
        } for(ExamenSessie e : b.getToegewezenSessies()){
            b.getToegewezenSessies().add(kop.getTeWisselenExamenSessie());
        }
    }
        
              
                
        
    
   
    public String getWisselAssistent(){
        return beschikbareAssistenten.getSelectedValue();
    }
    public String getExamenSessiesBeschikbaar(){
        return beschikbareAssistenten.getSelectedValue();
    }
    public int AssistenNummerNemen(String a){
        String[] b = a.split("-");
        int assNr = Integer.parseInt(b[0]);
        return assNr;
    }
       
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> beschikbareAssistenten;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
