/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hir;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author matthieu
 */
public class ExamenGUISurveilantWisselen extends javax.swing.JFrame {

    /**
     * Creates new form ExamenGUI2
     */
    public ExamenGUISurveilantWisselen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        assistenNummer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        examenSessies = new javax.swing.JList<>();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("NIEUWE SURVEILLANTIE");

        jLabel3.setText("Uw examensessies:");

        assistenNummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistenNummerActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Geef uw assistentnummmer:");

        jScrollPane1.setViewportView(examenSessies);

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submit)
                            .addComponent(assistenNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assistenNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addComponent(submit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assistenNummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assistenNummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assistenNummerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       EXAMENGUISurveillantWisselen2 a = new EXAMENGUISurveillantWisselen2();
       a.show();
       
       
       
       
       
       
       
       
       
       
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    int AssNr = getAssistentNummer();
        try {
            geefExamensessiesWeer(AssNr);
        } catch (DBException ex) {
            Logger.getLogger(ExamenGUISurveilantWisselen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    
    
    public int getAssistentNummer(){
        return Integer.parseInt(assistenNummer.getText());
    }
    
    public void geefExamensessiesWeer(int AssNr) throws DBException{
        ArrayList<ExamenSessie> alleExamenSessies = new ArrayList<>();
        alleExamenSessies.addAll(DBAssistent.getAssistent(AssNr).getToegewezenSessies());
        DefaultListModel dlm = new DefaultListModel();
        for(ExamenSessie a : alleExamenSessies){
            dlm.addElement(a.toString());
        }
        examenSessies.setModel(dlm);
       /* for (int i = 0; i < DBAssistent.getAssistent(getAssistentNummer()).getToegewezenSessies().size(); i++) {
            
           alleExamenSessies.add(DBAssistent.getAssistent(getAssistentNummer()).getToegewezenSessies().get(i).getSlot().toString());
            
        }
        return alleExamenSessies;
}*/
    }
    /*public void setExamenSessies() throws DBException{
        DefaultListModel dlm = new DefaultListModel();
        for(ExamenSessie a : geefExamensessiesWeer()){
            dlm.addElement(a);
        }
        examenSessies.setModel(dlm);
    }*/
    /*public ExamenSessie getTeWisselenExamenSessie() throws DBException{
        String a= examenSessies.getSelectedValue();
        for(Assistent b: DBAssistent.getAssistenten()){
            for(ExamenSessie c : b.getToegewezenSessies()){
                if(c.toString().equals(a)){
                    return c;
    }
            }
        }
        return null;
    }*/
    public ExamenSessie getTeWisselenExamenSessie(){
       return examenSessies.getSelectedValue();
        
    }
                

                  
                    
         
        
        
        
        



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assistenNummer;
    private java.awt.Choice choice1;
    private javax.swing.JList<ExamenSessie> examenSessies;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    

    

}
