/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hir;

/**
 *
 * @author matthieu
 */
public class EXAMENGUIMENU extends javax.swing.JFrame {

    /**
     * Creates new form EXAMENGUIMENU
     */
    public EXAMENGUIMENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        surveillantieWisselen = new javax.swing.JRadioButton();
        ExamenSessieAanmaken = new javax.swing.JRadioButton();
        examenRoosterAfdrukken = new javax.swing.JRadioButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("WELKE ACTIE WILT U UITVOEREN?");

        surveillantieWisselen.setText("Surveillantie wisselen");
        surveillantieWisselen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surveillantieWisselenActionPerformed(evt);
            }
        });

        ExamenSessieAanmaken.setText("Examensessie aanmaken");
        ExamenSessieAanmaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamenSessieAanmakenActionPerformed(evt);
            }
        });

        examenRoosterAfdrukken.setText("Examenrooster afdrukken");
        examenRoosterAfdrukken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examenRoosterAfdrukkenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examenRoosterAfdrukken)
                    .addComponent(ExamenSessieAanmaken)
                    .addComponent(surveillantieWisselen)
                    .addComponent(jLabel1))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(surveillantieWisselen)
                .addGap(31, 31, 31)
                .addComponent(ExamenSessieAanmaken)
                .addGap(35, 35, 35)
                .addComponent(examenRoosterAfdrukken)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void surveillantieWisselenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surveillantieWisselenActionPerformed
        ExamenGUISurveilantWisselen a = new ExamenGUISurveilantWisselen();
        a.show();
    }//GEN-LAST:event_surveillantieWisselenActionPerformed

    private void ExamenSessieAanmakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamenSessieAanmakenActionPerformed
      ExamenGUI a = new ExamenGUI();
      a.show();
    }//GEN-LAST:event_ExamenSessieAanmakenActionPerformed

    private void examenRoosterAfdrukkenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examenRoosterAfdrukkenActionPerformed
      EXAMENGUIROOSTERAFDRUKKEN  a = new EXAMENGUIROOSTERAFDRUKKEN();
      a.show();
    }//GEN-LAST:event_examenRoosterAfdrukkenActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ExamenSessieAanmaken;
    private javax.swing.JRadioButton examenRoosterAfdrukken;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButton surveillantieWisselen;
    // End of variables declaration//GEN-END:variables
}
