/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hirgroep11;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author matthieu
 */
public class GuiMENU extends javax.swing.JFrame {

    /**
     * Creates new form EXAMENGUIMENU
     */
    public GuiMENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        ButtonSurveillantieWisselen = new javax.swing.JButton();
        ButtonExamenInplannen = new javax.swing.JButton();
        ButtonExamenRoosterAfdrukken = new javax.swing.JButton();
        ButtonExamenUitplannen = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("WELKE ACTIE WILT U UITVOEREN?");

        ButtonSurveillantieWisselen.setText("Surveillantie wisselen");
        ButtonSurveillantieWisselen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSurveillantieWisselenActionPerformed(evt);
            }
        });

        ButtonExamenInplannen.setText("Examen inplannen");
        ButtonExamenInplannen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExamenInplannenActionPerformed(evt);
            }
        });

        ButtonExamenRoosterAfdrukken.setText("Examenrooster afdrukken");
        ButtonExamenRoosterAfdrukken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExamenRoosterAfdrukkenActionPerformed(evt);
            }
        });

        ButtonExamenUitplannen.setText("Examen uitplannen");
        ButtonExamenUitplannen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExamenUitplannenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonExamenUitplannen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonExamenRoosterAfdrukken, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(ButtonSurveillantieWisselen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonExamenInplannen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(ButtonExamenInplannen)
                .addGap(13, 13, 13)
                .addComponent(ButtonExamenUitplannen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonSurveillantieWisselen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonExamenRoosterAfdrukken)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSurveillantieWisselenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSurveillantieWisselenActionPerformed
        GuiSURVEILLANTWISSELEN surveillantWisselen = new GuiSURVEILLANTWISSELEN();
        surveillantWisselen.show();
        try {
            surveillantWisselen.setSurveillantenLijst();
        } catch (DBException ex) {
            Logger.getLogger(GuiMENU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonSurveillantieWisselenActionPerformed

    private void ButtonExamenInplannenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExamenInplannenActionPerformed
       GuiEXAMENINPLANNEN examenInplannen = new GuiEXAMENINPLANNEN();
       examenInplannen.show();
        try {
            examenInplannen.setFaculteitLijst();
        } catch (DBException ex) {
            Logger.getLogger(GuiMENU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonExamenInplannenActionPerformed

    private void ButtonExamenRoosterAfdrukkenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExamenRoosterAfdrukkenActionPerformed
        GuiROOSTERAFDRUKKEN  roosterAfdrukken;
        try {
            roosterAfdrukken = new GuiROOSTERAFDRUKKEN();
            roosterAfdrukken.show();
        } catch (DBException ex) {
            Logger.getLogger(GuiMENU.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ButtonExamenRoosterAfdrukkenActionPerformed

    private void ButtonExamenUitplannenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExamenUitplannenActionPerformed
        GuiEXAMENUITPLANNEN examenUitplannen = new GuiEXAMENUITPLANNEN();
        examenUitplannen.show();
        try {
            examenUitplannen.setFaculteitLijst();
        } catch (DBException ex) {
            Logger.getLogger(GuiMENU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonExamenUitplannenActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExamenInplannen;
    private javax.swing.JButton ButtonExamenRoosterAfdrukken;
    private javax.swing.JButton ButtonExamenUitplannen;
    private javax.swing.JButton ButtonSurveillantieWisselen;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    // End of variables declaration//GEN-END:variables
}
